POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3NzU2ZmExY2IyNmExNmNhMTFmZDliOSIsImlhdCI6MTczNTgwNDI5N30.4kx1YoxcfuvVxqbG3jKiJPVePrkcjJMdoypj0YdBeoA

{
    "content": "user is of the note",
    "important": true,
    "userId": "67756fa1cb26a16ca11fd9b9"
}